sl24_homepage:
    path: /
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_login:
    path: /login
    defaults: { _controller: Sl24Bundle:Index:login }

sl24_login_check:
    path: /login_check
    defaults: { _controller: Sl24Bundle:Index:loginCheck }

sl24_logout:
    path: /logout

#############################################################################
######################## Begin of Meeting routing ###########################
#############################################################################

sl24_getMeetings:
    pattern: /user/{user_id}/meetings
    defaults: { _controller: Sl24Bundle:Meeting:getMeetings }

sl24_getMeeting:
    pattern: /meeting/get/{meeting_id}
    defaults: { _controller: Sl24Bundle:Meeting:getMeeting }

sl24_addMeeting:
    path: /meetings/add
    defaults: { _controller: Sl24Bundle:Meeting:addNewMeeting }

sl24_addMounth:
    path: /mounth/add
    defaults: { _controller: Sl24Bundle:Mounth:addMounth }

sl24_saveMeeting:
    pattern: /meeting/save/{meeting_id}
    defaults: { _controller: Sl24Bundle:Meeting:editMeeting }

sl24_removeMeeting:
    pattern: /meeting/remove/{meeting_id}
    defaults: { _controller: Sl24Bundle:Meeting:removeMeeting }

sl24_getMeetingsInfo:
    path: /meetings/getmeetingsInfo
    defaults: { _controller: Sl24Bundle:Meeting:getMeetingsInfo }

sl_24_get_posts_meetings:
    pattern: /getMeetingPosts/{meeting_id}
    defaults: { _controller: Sl24Bundle:MeetingPost:getPosts }

sl_24_add_post_meeting:
    pattern: /addMeetingPost/{meeting_id}
    defaults: { _controller: Sl24Bundle:MeetingPost:addPost }

sl_24_edit_post_meeting:
    pattern: /editMeetingPost/{post_id}
    defaults: { _controller: Sl24Bundle:MeetingPost:editPost }

#############################################################################
######################### End of Meeting routing ############################
#############################################################################


#############################################################################
######################### Begin of Task routing #############################
#############################################################################

sl_24_get_tasks:
    path: /getTasks
    defaults: { _controller: Sl24Bundle:Task:getTasks }

sl_24_get_task:
    path: /getTask/{task_id}
    defaults: { _controller: Sl24Bundle:Task:getTask }

sl_24_get_statuses:
    path: /getStatuses
    defaults: { _controller: Sl24Bundle:Task:getStatuses }

sl_24_save_task_info:
    path: /saveTaskInfo
    defaults: { _controller: Sl24Bundle:Task:saveTaskInfo }

sl_24_add_task:
    path: /addTask
    defaults: { _controller: Sl24Bundle:Task:addTask }

sl_24_delete_task:
    path: /deleteTask
    defaults: { _controller: Sl24Bundle:Task:deleteTask }

sl_24_get_task_posts:
    pattern: /getTaskPosts/{task_id}
    defaults: { _controller: Sl24Bundle:TaskPost:getPosts }

sl_24_add_task_post:
    pattern: /addTaskPost/{task_id}
    defaults: { _controller: Sl24Bundle:TaskPost:addPost }

sl_24_edit_task_post:
    pattern: /editTaskPost/{post_id}
    defaults: { _controller: Sl24Bundle:TaskPost:editPost }

#############################################################################
######################### End of Task routing ###############################
#############################################################################



sl_24_get_team:
    path: /getTeam
    defaults: { _controller: Sl24Bundle:Team:GetTeams }

sl_24_registration:
    path: /register_new_user
    defaults: { _controller: Sl24Bundle:Registration:registration }

sl_24_get_article:
    path: /article/get
    defaults: { _controller: Sl24Bundle:Article:getArticles }


sl_24_get_full_article:
    path: /article/get/full/{id}
    defaults: { _controller: Sl24Bundle:Article:getFullArticles }

sl_24_add_article:
    path: /article/add
    defaults: { _controller: Sl24Bundle:Article:addArticles }

sl_24_get_articles_page:
    path: /article
    defaults: { _controller: Sl24Bundle:Index:index }




#############################################################################
########################### Default Routes Block ############################
############# Please add your SHIT code ABOVE this block, thx... ############
#############################################################################

sl24_default:
    pattern: /consultant/{some}
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_default_2level:
    pattern: /consultant/{some}/{some1}
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_default_3level:
    pattern: /consultant/{some}/{some1}/{some2}
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_default_4level:
    pattern: /consultant/{some}/{some1}/{some2}/{some3}
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_default_5level:
    pattern: /consultant/{some}/{some1}/{some2}/{some3}/{some4}
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_default_6level:
    pattern: /consultant/{some}/{some1}/{some2}/{some3}/{some4}/{some5}
    defaults: { _controller: Sl24Bundle:Index:index }

#############################################################################

sl24_default_1_level:
    pattern: /consultant/
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_default_2_level:
    pattern: /consultant/{some}/
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_default_3_level:
    pattern: /consultant/{some}/{some1}/
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_default_4_level:
    pattern: /consultant/{some}/{some1}/{some2}/
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_default_5_level:
    pattern: /consultant/{some}/{some1}/{some2}/{some3}/
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_default_6_level:
    pattern: /consultant/{some}/{some1}/{some2}/{some3}/{some4}/
    defaults: { _controller: Sl24Bundle:Index:index }
#############################################################################
#############################################################################
#############################################################################
