sl24_homepage:
    path: /
    defaults: { _controller: Sl24Bundle:Index:index }

sl24_login:
    path: /login
    defaults: { _controller: Sl24Bundle:Index:login }

sl24_login_check:
    path: /login_check
    defaults: { _controller: Sl24Bundle:Index:loginCheck }

sl24_logout:
    path: /logout

sl24_getMeetings:
    pattern: /user/{user_id}/meetings
    defaults: { _controller: Sl24Bundle:Meeting:getMeetings }

sl24_getMeeting:
    pattern: /meeting/{meeting_id}
    defaults: { _controller: Sl24Bundle:Meeting:getMeeting }

sl24_addMeeting:
    path: /meetings/add
    defaults: { _controller: Sl24Bundle:Meeting:addNewMeeting }

sl24_getMeetingsInfo:
    path: /meetings/getmeetingsInfo
    defaults: { _controller: Sl24Bundle:Meeting:getMeetingsInfo }

sl_24_get_tasks:
    path: /getTasks
    defaults: { _controller: Sl24Bundle:Task:getTasks }

sl24_default:
    pattern: /{some}
    defaults: { _controller: Sl24Bundle:Index:index }
